### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by hazzino** [PLi-metas/dvbsnoop#1]
Hi t here i'm having probs compiling dvbsnoop
/src/private/libprivate.a(userdefs.o):(.data.rel+0x18): undefined reference to `getPrivate_BskybUK'
collect2: error: ld returned 1 exit status
Makefile:268: recipe for target 'dvbsnoop' failed
make[2]: *** [dvbsnoop] Error 1
Doing a .configure i see no error
Ubuntu 18,  done a git clone under Download directory

**Comment by persianpros** [comment]
We're using PLi's OE with no problem: https://github.com/OpenPLi/openpli-oe-core/blob/develop/meta-openpli/recipes-multimedia/dvbsnoop/dvbsnoop.bb
